Add Matt
Lovely-Development-Team/tildy.dev pull request #25
Opened 2021-09-15 19:39 UTC by RosemaryOrchard

2021-09-15 19:40 UTC, benbacardi approved these changes

2021-09-15 19:44 UTC, benbacardi commented on docs/_data/members.json
> +			"link": "https://mattcooksey.me"
Change to http://

2021-09-15 19:44 UTC, mattcooksey12 requested changes
change https to http

2021-09-15 19:56 UTC, mattcooksey12 approved these changes

2021-09-16 22:08 UTC, klmatthews4 approved these changes

2021-09-16 22:08 UTC, merged